# --- Main Colors ---
background            #111418
foreground            #e1e2e8
cursor                #e1e2e8
cursor_text_color     #111418

selection_background  #3c4858
selection_foreground  #d7e3f8

url_color             #d8bde3

# --- ANSI Colors ---
color0                #111418
color1                #ffb4ab
color2                #d8bde3
color3                #bbc7db
color4                #a3c9fe
color5                #d8bde3
color6                #bbc7db
color7                #e1e2e8

color8                #43474e
color9                #93000a
color10               #533f5e
color11               #3c4858
color12               #1d4875
color13               #3c4858
color14               #533f5e
color15               #c3c6cf

# --- Starship Prompt Bubbles ---
color255              #1d4875
color254              #a3c9fe
color253              #3c4858
color252              #bbc7db
color251              #533f5e
color250              #d8bde3
color249              #93000a
color248              #ffb4ab

color232              #d3e4ff
color233              #00315b
color234              #d7e3f8
color235              #263141
color236              #f4d9ff
color237              #3c2947
color238              #ffdad6
color239              #690005
color240              #d3e4ff

# Matched with unthemed light/dark
color243              #a3c9fe
color244              #ffb4ab
color245              #43474e

# --- UI Elements ---
active_tab_foreground   #00315b
active_tab_background   #a3c9fe
inactive_tab_foreground #d3e4ff
inactive_tab_background #1d4875

active_border_color     #a3c9fe
inactive_border_color   #8d9199

# --- Marks ---
mark1_foreground        #001c38
mark1_background        #d3e4ff
mark2_foreground        #101c2b
mark2_background        #d7e3f8
mark3_foreground        #261431
mark3_background        #f4d9ff
