# --- Main Colors ---
background            #11140e
foreground            #e2e3d9
cursor                #e2e3d9
cursor_text_color     #11140e

selection_background  #404a34
selection_foreground  #dbe7c8

url_color             #a0cfcc

# --- ANSI Colors ---
color0                #11140e
color1                #ffb4ab
color2                #a0cfcc
color3                #bfcbad
color4                #afd18c
color5                #a0cfcc
color6                #bfcbad
color7                #e2e3d9

color8                #44483e
color9                #93000a
color10               #1e4e4c
color11               #404a34
color12               #334e18
color13               #404a34
color14               #1e4e4c
color15               #c4c8ba

# --- Starship Prompt Bubbles ---
color255              #334e18
color254              #afd18c
color253              #404a34
color252              #bfcbad
color251              #1e4e4c
color250              #a0cfcc
color249              #93000a
color248              #ffb4ab

color232              #cbeea5
color233              #1d3703
color234              #dbe7c8
color235              #29331f
color236              #bbece9
color237              #003735
color238              #ffdad6
color239              #690005
color240              #cbeea5

# Matched with unthemed light/dark
color243              #afd18c
color244              #ffb4ab
color245              #44483e

# --- UI Elements ---
active_tab_foreground   #1d3703
active_tab_background   #afd18c
inactive_tab_foreground #cbeea5
inactive_tab_background #334e18

active_border_color     #afd18c
inactive_border_color   #8e9285

# --- Marks ---
mark1_foreground        #0e2000
mark1_background        #cbeea5
mark2_foreground        #151e0b
mark2_background        #dbe7c8
mark3_foreground        #00201f
mark3_background        #bbece9
