$image = /home/sparsha/Pictures/Wallpapers/476288.jpg

$background = rgba(15130bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(333027ff)

$inverse_primary = rgba(6c5e0fff)

$inverse_surface = rgba(e8e2d4ff)

$on_background = rgba(e8e2d4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(393000ff)

$on_primary_container = rgba(f7e388ff)

$on_primary_fixed = rgba(211b00ff)

$on_primary_fixed_variant = rgba(524600ff)

$on_secondary = rgba(363016ff)

$on_secondary_container = rgba(ede2bcff)

$on_secondary_fixed = rgba(201c04ff)

$on_secondary_fixed_variant = rgba(4d472bff)

$on_surface = rgba(e8e2d4ff)

$on_surface_variant = rgba(cdc6b4ff)

$on_tertiary = rgba(133723ff)

$on_tertiary_container = rgba(c4eccfff)

$on_tertiary_fixed = rgba(002110ff)

$on_tertiary_fixed_variant = rgba(2b4e39ff)

$outline = rgba(969080ff)

$outline_variant = rgba(4a4739ff)

$primary = rgba(d9c76fff)

$primary_container = rgba(524600ff)

$primary_fixed = rgba(f7e388ff)

$primary_fixed_dim = rgba(d9c76fff)

$scrim = rgba(000000ff)

$secondary = rgba(d0c6a2ff)

$secondary_container = rgba(4d472bff)

$secondary_fixed = rgba(ede2bcff)

$secondary_fixed_dim = rgba(d0c6a2ff)

$shadow = rgba(000000ff)

$source_color = rgba(706428ff)

$surface = rgba(15130bff)

$surface_bright = rgba(3c3930ff)

$surface_container = rgba(222017ff)

$surface_container_high = rgba(2c2a21ff)

$surface_container_highest = rgba(37352bff)

$surface_container_low = rgba(1e1c13ff)

$surface_container_lowest = rgba(100e07ff)

$surface_dim = rgba(15130bff)

$surface_tint = rgba(d9c76fff)

$surface_variant = rgba(4a4739ff)

$tertiary = rgba(a9d0b4ff)

$tertiary_container = rgba(2b4e39ff)

$tertiary_fixed = rgba(c4eccfff)

$tertiary_fixed_dim = rgba(a9d0b4ff)

