# --- Run hyprlock ---
listener {
    timeout = 30
    on-timeout = hyprlock
    on-resume = hyprctl dispatch dpms on 
}

# --- Turn off display ---
listener {
    timeout = 60
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# --- Suspend system ---
listener {
    timeout = 120
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on 
}
